#!/usr/bin/env bash
set -euo pipefail

# test-core.sh -- E2E test for core Gateway API resources
#
# Validates that YAML generated by eg-install, eg-gateway, and eg-route skills
# produces working Kubernetes resources. Assumes setup-cluster.sh has already
# been run.
#
# Usage:
#   ./tests/e2e/test-core.sh

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

# --- Find repo root ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
EXTRACT_SCRIPT="${REPO_ROOT}/tests/extract-yaml.sh"

# --- Test framework ---
TESTS_RUN=0
TESTS_PASSED=0
TESTS_FAILED=0
TIMEOUT=120

run_test() {
  local name="$1"
  local func="$2"
  TESTS_RUN=$((TESTS_RUN + 1))

  echo -e "${CYAN}TEST: ${name}${NC}"

  if eval "$func"; then
    TESTS_PASSED=$((TESTS_PASSED + 1))
    echo -e "  ${GREEN}PASS${NC}"
  else
    TESTS_FAILED=$((TESTS_FAILED + 1))
    echo -e "  ${RED}FAIL${NC}"
    dump_debug_info
  fi
  echo ""
}

# Wait for a condition with timeout
wait_for() {
  local description="$1"
  shift
  local timeout="${TIMEOUT}"
  local elapsed=0

  echo -e "  Waiting for: ${description} (timeout: ${timeout}s)"
  while [[ $elapsed -lt $timeout ]]; do
    if eval "$@" 2>/dev/null; then
      return 0
    fi
    sleep 2
    elapsed=$((elapsed + 2))
  done

  echo -e "  ${RED}Timed out waiting for: ${description}${NC}"
  return 1
}

# Print diagnostic info for debugging failures
dump_debug_info() {
  echo -e "  ${YELLOW}--- Debug Info ---${NC}"
  echo -e "  ${YELLOW}Gateway status:${NC}"
  kubectl get gateway -n default -o wide 2>/dev/null || true
  echo -e "  ${YELLOW}Gateway conditions:${NC}"
  kubectl get gateway -n default -o jsonpath='{range .items[*]}{.metadata.name}: {.status.conditions[*].type}={.status.conditions[*].status}{"\n"}{end}' 2>/dev/null || true
  echo -e "  ${YELLOW}Envoy pods:${NC}"
  kubectl get pods -n envoy-gateway-system 2>/dev/null || true
  echo -e "  ${YELLOW}Events (last 20):${NC}"
  kubectl get events -n default --sort-by='.lastTimestamp' 2>/dev/null | tail -20 || true
  echo -e "  ${YELLOW}--- End Debug ---${NC}"
}

# --- Preflight checks ---
echo -e "${BOLD}Core Resource E2E Tests${NC}"
echo -e "${BOLD}========================================${NC}"
echo ""

# Verify cluster is reachable
if ! kubectl cluster-info &>/dev/null; then
  echo -e "${RED}Error: Kubernetes cluster is not reachable. Run setup-cluster.sh first.${NC}"
  exit 1
fi

# Verify extract script exists
if [[ ! -x "$EXTRACT_SCRIPT" ]]; then
  echo -e "${RED}Error: extract-yaml.sh not found or not executable at ${EXTRACT_SCRIPT}${NC}"
  exit 1
fi

# --- Extract YAML from skills ---
echo -e "${CYAN}Extracting YAML from core skills...${NC}"
YAML_DIR="/tmp/envoy-skills-yaml-e2e-core"

SKILLS_BASE="${REPO_ROOT}/gateway/adopters/skills"
SKILL_FILES=()
for skill in eg-install eg-gateway eg-route; do
  skill_file="${SKILLS_BASE}/${skill}/SKILL.md"
  if [[ -f "$skill_file" ]]; then
    SKILL_FILES+=("$skill_file")
  else
    echo -e "${YELLOW}Warning: Skill file not found: ${skill_file}${NC}"
  fi
done

if [[ ${#SKILL_FILES[@]} -gt 0 ]]; then
  "${EXTRACT_SCRIPT}" --outdir "$YAML_DIR" "${SKILL_FILES[@]}"
fi
echo ""

# --- Test 1: GatewayClass is accepted ---
test_gatewayclass_accepted() {
  # The GatewayClass 'eg' should already exist from setup-cluster.sh
  # Verify it's accepted by the controller
  local status
  status="$(kubectl get gatewayclass eg -o jsonpath='{.status.conditions[?(@.type=="Accepted")].status}' 2>/dev/null || echo "")"
  if [[ "$status" == "True" ]]; then
    echo -e "  GatewayClass 'eg' is Accepted"
    return 0
  fi

  # If not yet accepted, wait briefly
  wait_for "GatewayClass 'eg' to be Accepted" \
    '[ "$(kubectl get gatewayclass eg -o jsonpath='"'"'{.status.conditions[?(@.type=="Accepted")].status}'"'"' 2>/dev/null)" = "True" ]'
}

# --- Test 2: Apply a basic HTTP Gateway and verify Programmed status ---
test_gateway_programmed() {
  # Apply a test Gateway using extracted YAML or inline
  local gw_name="e2e-test-gateway"

  kubectl apply -f - <<EOF
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ${gw_name}
  namespace: default
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: 8080
      allowedRoutes:
        namespaces:
          from: Same
EOF

  # Wait for Programmed status
  wait_for "Gateway '${gw_name}' to be Programmed" \
    '[ "$(kubectl get gateway '"${gw_name}"' -n default -o jsonpath='"'"'{.status.conditions[?(@.type=="Programmed")].status}'"'"' 2>/dev/null)" = "True" ]'
  local result=$?

  # Clean up
  kubectl delete gateway "${gw_name}" -n default --ignore-not-found &>/dev/null || true

  return $result
}

# --- Test 3: Apply a basic HTTPRoute and verify Accepted status ---
test_httproute_accepted() {
  # Use the test-gateway from setup-cluster.sh
  local route_name="e2e-test-route"

  kubectl apply -f - <<EOF
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ${route_name}
  namespace: default
spec:
  parentRefs:
    - name: test-gateway
  hostnames:
    - "e2e-test.example.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /e2e
      backendRefs:
        - name: test-backend
          port: 80
EOF

  # Wait for Accepted status
  wait_for "HTTPRoute '${route_name}' to be Accepted" \
    '[ "$(kubectl get httproute '"${route_name}"' -n default -o jsonpath='"'"'{.status.parents[0].conditions[?(@.type=="Accepted")].status}'"'"' 2>/dev/null)" = "True" ]'
  local result=$?

  # Clean up
  kubectl delete httproute "${route_name}" -n default --ignore-not-found &>/dev/null || true

  return $result
}

# --- Test 4: Port-forward and curl for 200 response ---
test_http_connectivity() {
  # Use the test-gateway and test-route from setup-cluster.sh
  local eg_ns="envoy-gateway-system"
  local local_port=19080

  # Find the Envoy service for test-gateway
  # Try gateway.envoyproxy.io/owning-gateway-name first, then gateway.networking.k8s.io/gateway-name (GEP-1762)
  local envoy_svc
  envoy_svc="$(kubectl get svc -n "${eg_ns}" \
    -l gateway.envoyproxy.io/owning-gateway-name=test-gateway \
    -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || echo "")"
  if [[ -z "$envoy_svc" ]]; then
    envoy_svc="$(kubectl get svc -n "${eg_ns}" \
      -l gateway.networking.k8s.io/gateway-name=test-gateway \
      -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || echo "")"
  fi

  if [[ -z "$envoy_svc" ]]; then
    echo -e "  ${RED}Could not find Envoy service for test-gateway${NC}"
    echo -e "  ${YELLOW}Available services:${NC}"
    kubectl get svc -n "${eg_ns}" -o wide 2>/dev/null || true
    return 1
  fi

  # Start port-forward in background
  kubectl port-forward -n "${eg_ns}" "svc/${envoy_svc}" "${local_port}:80" &>/dev/null &
  local pf_pid=$!

  # Give port-forward time to establish
  sleep 5

  # Verify port-forward is running
  if ! kill -0 "$pf_pid" 2>/dev/null; then
    echo -e "  ${RED}Port-forward process died${NC}"
    return 1
  fi

  # Curl the backend through the Gateway with retries
  local http_code="000"
  local attempt
  for attempt in 1 2 3; do
    http_code="$(curl -s -o /dev/null -w '%{http_code}' \
      --max-time 10 \
      -H 'Host: test.example.com' \
      "http://localhost:${local_port}/" 2>/dev/null || echo "000")"
    if [[ "$http_code" == "200" ]]; then
      break
    fi
    echo -e "  ${YELLOW}Attempt ${attempt}: HTTP ${http_code}, retrying...${NC}"
    sleep 3
  done

  # Kill port-forward
  kill "$pf_pid" 2>/dev/null || true
  wait "$pf_pid" 2>/dev/null || true

  if [[ "$http_code" == "200" ]]; then
    echo -e "  Received HTTP ${http_code} from backend via Gateway"
    return 0
  else
    echo -e "  ${RED}Expected HTTP 200, got HTTP ${http_code}${NC}"
    return 1
  fi
}

# --- Wait for test-gateway from setup-cluster.sh to be ready ---
# Tests 3 and 4 depend on test-gateway being Programmed
echo -e "${CYAN}Waiting for setup test-gateway to be Programmed...${NC}"
wait_for "test-gateway to be Programmed" \
  '[ "$(kubectl get gateway test-gateway -n default -o jsonpath='"'"'{.status.conditions[?(@.type=="Programmed")].status}'"'"' 2>/dev/null)" = "True" ]' || {
  echo -e "${YELLOW}Warning: test-gateway not Programmed yet. Tests 3 and 4 may fail.${NC}"
}
echo ""

# --- Run tests ---
run_test "GatewayClass 'eg' is accepted" test_gatewayclass_accepted
run_test "HTTP Gateway reaches Programmed status" test_gateway_programmed
run_test "HTTPRoute is accepted by Gateway" test_httproute_accepted
run_test "HTTP request through Gateway returns 200" test_http_connectivity

# --- Summary ---
echo -e "${BOLD}========================================${NC}"
echo -e "${BOLD}Core E2E Test Summary${NC}"
echo -e "${BOLD}========================================${NC}"
echo -e "Tests run:    ${TESTS_RUN}"
echo -e "${GREEN}Passed:       ${TESTS_PASSED}${NC}"
echo -e "${RED}Failed:       ${TESTS_FAILED}${NC}"
echo ""

if [[ $TESTS_FAILED -gt 0 ]]; then
  echo -e "${RED}SOME TESTS FAILED${NC}"
  exit 1
else
  echo -e "${GREEN}ALL TESTS PASSED${NC}"
  exit 0
fi
